In [71]:
import random 
import math
# import pandas as pd
import random
# import csv
from copy import deepcopy
import numpy as np
# import matplotlib.pyplot as plt

In [111]:
def crear_genes(n, m): # 5=n=y, 10=m=x
    # Crea un individuo
  gen = np.zeros((n, m))
  for i in range(n):
    pos = random.randint(0, 9)
    gen[i, pos] = 1
  return gen 

def crear_poblacion(numero_poblacion):
    # Crea una poblacion nueva de individuos
  
    return [crear_genes(n, m) for i in range(numero_poblacion)]


In [116]:
n, m = 5, 10
poblacion = 10
gen = crear_genes(5,10)
print(gen)
poblacion = crear_poblacion(10)
print(poblacion[2])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [115]:
# indice = poblacion[0].index(1)
def obtener_indice(poblacion):
  indices = []
  indice_total = []
  for poblacion in poblacion:
    for gen in poblacion:
      for i in range(1,5):
        indice = gen[i].index(1)
        indices.append([i,indice])
    indice_total.append(indices)
    indices=[]

  return indice_total

In [ ]:
def calcular_fitness(indices):
  for i in range(1,10): 
    fitnes = ((x2-x1)**2 + (y2-y1)**2)**(1/2)
  return fitnes

In [ ]:

def selecciona_padres(poblacion, n_padres): # selecciona los primeros n_padres = 100 de la poblacion
  ordenados_por_distancia = sorted(poblacion)
  seleccionados = ordenados_por_distancia[:n_padres]
  return seleccionados 


def _cruza_dos_padres(padre1, padre2): 
  hijo = padre2
  elementos = 3
  for posicion_p1, valor_p1 in enumerate(padre1):
    posicion_2 = random.randint(min, max) # devuelve el primer elemento encontrado
    hijo[posicion_2] = hijo[posicion_p1]
    hijo[posicion_p1] = valor_p1
  return hijo


def reproduccion(mejores_padres, nuevo_tamano_poblacion): # se crusan dos padres elegidos de los mejores padres elegidos  
  hijos_faltantes = nuevo_tamano_poblacion - len(mejores_padres)
  nuevos_hijos = []
  for i in range(hijos_faltantes):
    padre1, padre2 = random.sample(mejores_padres, 2)
    # padre1, padre2 = mejores_padres[i], mejores_padres[i+1]
    nuevo_hijo = _cruza_dos_padres(padre1, padre2)
    nuevos_hijos.append(nuevo_hijo)
  return nuevos_hijos


def mutacion(nuevos_hijos, probavilidad_mutacion): # la mutacion consiste en cambiar una ciudad por otra
  hijos_mutados = []
  for hijo in nuevos_hijos:
    productos = deepcopy(hijo.productos)
    if probavilidad_mutacion > random.random():
      cambiar_de = random.randint(0, len(productos)-1)
      cambiar_a = random.randint(0, len(productos)-1)
      while cambiar_de == cambiar_a: # para que no se eligan las mismas productos
        cambiar_a = random.randint(0, len(productos)-1)
      ciudad_a_cambiar  = productos[cambiar_a]
      productos[cambiar_a] = productos[cambiar_de]
      productos[cambiar_de] = ciudad_a_cambiar
  # hijos_mutados.append(Ruta(productos))
  return hijos_mutados


In [ ]:
valor_minimo_gen = 10
valor_maximo_gen = 100
numero_productos= 10
numero_proveedores = 10


poblacion = crear_proveedores(numero_productos)
print
mejores_padres = selecciona_padres(poblacion, 5)
print(mejores_padres)
reproduccion = reproduccion(mejores_padres,numero_proveedores)

In [ ]:
if __name__ == "__main__":
  # minimo y maximo para generar los productos aleatoriamente entre ese rango
  valor_minimo_gen = 10
  valor_maximo_gen = 100
  numero_productos = 10 # numero de genes
  numero_proveedores = 10 # numero de poblacion
  # numero_proveedores = 70 #cantidad de los proveedores
  n_padres_seleccionados = int(numero_proveedores/3) # seleccion padres para la mescla
  probavilidad_mutacion = 0.6 # probavlidad para la mutacion
  # cantidad_cruce = 0,5  # cuantos padres pueden hacer el cruce del total de la poblacion
  numero_generaciones = 5000

  #CREACION DE LAS productos Y LA POBLACION
  pruductos_generados = crear_productos(valor_minimo_gen, valor_maximo_gen)

  poblacion = crear_proveedores(numero_productos)
  # print('poblacion seleccionada: ',poblacion[0])


  mejor_proveedor = 0
  contador = 0
  for id_generacion in range(numero_generaciones):

    mejor_product = sorted(poblacion)[0]
    if contador == 1000: # Si un mismo fitnes se repite 500 veces se corta la ejecicucion
      break
    else: 
      if mejor_proveedor == mejor_product:
        contador += 1
      else:
        contador = 0
    mejor_proveedor = mejor_product


    print(f'Generacion: {id_generacion+1},   Mejor: {mejor_product} ')
    #SELECCION  LOS MEJORES PADRES
    seleccion_padres = selecciona_padres(poblacion, n_padres_seleccionados)
    #REPRODUCCION O CRUCE
    hijos_cruzados  = reproduccion(seleccion_padres, numero_proveedores)
    #MUTACION
    hijos_mutados = mutacion(hijos_cruzados, probavilidad_mutacion)
    #CREA NUEVA POBLACION
    poblacion  = seleccion_padres + hijos_mutados